### ISSUE TITLE
Code example in README not working / import failing

### ISSUE THREAD

**Issue by sonst-was** [nerdocs/pydifact#22]
Hi,

I tried to play around a little bit with pydifact but I seem to be unable to get it to run.

I successfully installed it via `pip` on Windows. When I then try to run the example from the README I get the following error:

```
Traceback (most recent call last):
  File "g:/test.py", line 1, in <module>
    from pydifact.segmentcollection import SegmentCollection
ModuleNotFoundError: No module named 'pydifact.segmentcollection'
```

Could you please help me on how to proceed?

**Comment by brucegibbins** [comment]
I found that whilst the version on pypi indicates it is the latest version it still uses the old class name 'message' rather than the new 'segmentcollection' name.
I suspect the build on pypi is and older version that does not match the current github source even though the version numbers match.
-------- Original message --------From: sonst-was <notifications@github.com> Date: 22/7/20  8:45 pm  (GMT+10:00) To: nerdocs/pydifact <pydifact@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [nerdocs/pydifact] Code example in README not working / import failing (#22) 
Hi,
I tried to play around a little bit with pydifact but I seem to be unable to get it to run.
I successfully installed it via pip on Windows. When I then try to run the example from the README I get the following error:
Traceback (most recent call last):
  File "g:/test.py", line 1, in <module>
    from pydifact.segmentcollection import SegmentCollection
ModuleNotFoundError: No module named 'pydifact.segmentcollection'

Could you please help me on how to proceed?

**Comment by sonst-was** [comment]
You appear to be correct. I cloned the repo and installed it from there and now it's working as expected.

Thanks for the help!

I'll leave this open so @nerdoc can consider updating the build on pypi.

**Comment by nerdoc** [comment]
Yes, I didn't update the version. the current git is more experimental, so I'd wait with an update on pypi. But I should updat ethe version on git. Is that ok to make it clearer?

**Comment by sonst-was** [comment]
That would help yes.

Although the code example is also present on the pypi project page. Someone only looking there won't know about the different versions.

**Comment by nerdoc** [comment]
Pfuh. At least I did *something* right ;-)
