### ISSUE TITLE
Handling of malformatted EDIFACT files

### ISSUE THREAD

**Issue by sonst-was** [nerdocs/pydifact#24]
Hello again :)

I've continued to play a bit with pydifact and I some unexpected behaviour when feeding malformatted EDIFACT files to pydifact 
I'm using the following code snippet for testing:
```
for segment in collection.segments:
    print('{}: {}'.format(segment.tag, segment.elements))
```

For example, when feeding 
`IMD+F++:::Item description 'for normals'`
This results in the following, which is somewhat ok, although you'd have to check for the validity of each tag:
```
IMD: ['F', '', ['', '', '', 'Item description ']]
for normals: []
```

But when I feed the following, pydifact doesn't handle the input gracefully and I'm presented a TypeError:
`IMD+F++:::Item description 'for :normals'`
Result:
```
Traceback (most recent call last):
  File "g:/GitHub/file.py", line 2, in <module>
    collection = SegmentCollection.from_file("G:\\GitHub\\DESADV_line_break.txt")
  File "C:\<...>Python\Python38-32\lib\site-packages\pydifact\segmentcollection.py", line 60, in from_file
    return cls.from_str(collection)
  File "C:\<...>Python\Python38-32\lib\site-packages\pydifact\segmentcollection.py", line 70, in from_str
    return cls.from_segments(segments)
  File "C:\<...>Python\Python38-32\lib\site-packages\pydifact\segmentcollection.py", line 85, in from_segments
    return cls().add_segments(segments)
  File "C:\<...>Python\Python38-32\lib\site-packages\pydifact\segmentcollection.py", line 115, in add_segments
    for segment in segments:
  File "C:\<...>Python\Python38-32\lib\site-packages\pydifact\parser.py", line 212, in convert_tokens_to_segments
    yield self.factory.create_segment(name, *segment)
  File "C:\<...>Python\Python38-32\lib\site-packages\pydifact\segments.py", line 78, in create_segment
    return Segment(name, *elements)
  File "C:\<...>Python\Python38-32\lib\site-packages\pydifact\segments.py", line 36, in __init__
    raise TypeError("'tag' argument must be a str")
TypeError: 'tag' argument must be a str
```

My question is, whether this is considered a bug or rather outside of the scope of pydifact (check for syntax validity somewhere else). And following up on that, what would you consider to be the best way of checking syntax validity (with or without pydifact)?

**Comment by sonst-was** [comment]
> To the last question - Im not sure myself how the best way of syntax checking would be. I am still searching for a good, machine readable source of EDIFACT syntax - to generate a model and validate against that. Any hints welcome.

The only thing I know (which doesn't mean much) that properly validates EDIFACT is [bots](http://bots.sourceforge.net/en/index.shtml). But the way it does this is by having a "grammar" for each EDIFACT type which specifies which segment is allowed after which segment and how often etc. Imo this is not a feasable way for pydifact.

Maybe I'll play a little bit with regex, just generic basic stuff which maybe catches the most issues.

> @sonst-was, is this ok for you? The EDISyntaxError is implemented basically, does this close this question for you?

This is fine for me yes - I think :D I'm not that good with programming myself because I don't do it often enough. Thats why I can't really say something about your approach (or help you in anyway)^^.

**Comment by nerdoc** [comment]
I'm no professional coder neither. So wee in the same boat ;-)
I recognized bots, but this was my main reason why I started anothre alternative, because it is a monstrum.
BUT: having rules which segments are allowed after which others, isn't a bad idea for the parser of pydifact.
I only have to few time ATM to implement this.

So validation should be done, but at a later point of time. TBH, we are at version 0.0.7 now... seems far from 1.0.

The next things I want to implement is supporting syntax versions 3 and 4, and to implement a higher level API for reading Messages and interchanges on top of the current nested list approach.

Regex is a bit slow IMHO and should be avoided at all means for repetitive calls here.
For now, each Segment should have an own class which does the validation under the hood. The plugin "framework" I implemented the last days allows this. The SegmentFactory then should take care of which segment it is and call the right class then. This should do the trick. It's just a matter of time: Each Segment (DTX, DTM, UNS etc) must have it's own class. Maybe I'll write a little more doc for that so anyone could implement his favourite Segment class and help with a PR easily.

**Comment by FelixSchwarz** [comment]
Btw: It would be nice if each segment had a reference to the exact input line (byte position start/end) to ease debugging. That might also help handling malformed files. (I just swapped our self-written edifact parser against pydifact and it was a pretty pleasant experience. However exact byte positions was the one feature we lost in that process.)

**Comment by nerdoc** [comment]
That's a really good idea - could you please open a new Issue for that?

**Comment by nerdoc** [comment]
did it already - I need to go on ;-)
